### PR TITLE
Add another method of chaining

### PR DESCRIPTION
**Pull request by natehitze**
Although it's a little more verbose, here's another way to facilitate chaining. It should work for _any_ type.

### CODE REVIEW

**Comment by smatsson** [comment]
This was actually one of the POCs I made when experimenting with how to build this. I have added a Wiki page with the different POCs I made and why I chose to go with Reflection.Emit (https://github.com/smatsson/Chainly/wiki/How-and-why%3F) (see section "Actions")

Instead of an interface I used an extension method which would return the original object directly. This way you could run it on any type and not care about interfaces or whatnot. I scrapped it because of the verbosity of the code. However as an extra feature to Chainly I can see it being implemented. 

I will gladly accept your PR if you could do some minor changes:
* Rename `CreateChain` to `Chain`. This way you would use new Asdf().Chain<IAsdf>() for an IL/typed chain and new Asdf().Chain() for an "action based" chain. 
* Replace the Result property with a Value method for consistency between the two.
* Replace the Assert.AreEqual calls in your tests with Shouldly that I used everywhere else in the tests ( Assert.AreEqual(a, b) => a.ShouldBe(b)).
* Add some example to Readme.md

I'm not a huge fan of the name `Then` as it confused me thinking about promises. It's good enough but if you can figure out a better name that would be appreciated (`Run`, `Do`, `Chain`?) 

Also, thanks for the PR and happy holidays! :)

**Comment by natehitze** [comment]
Thanks for looking through and providing feedback!

I did the renames as requested. I ended up going with Do instead of Then because it's shorter. Do you still have the benchmark prepared so you can run the action chain against it? The wiki page you mentioned is missing numbers for it and I'm pretty curious what the difference will be. Also did you have any thoughts on using the + operator as the .Do()?

I'll try to add examples to the readme in the next couple of days. Happy holidays to you as well!

**Comment by smatsson** [comment]
No problem at all mate. Thanks for contributing!

I'll accept the PR as soon as I'm back at a computer. 😊 I have the
benchmark code somewhere on my laptop. It was basically a for loop with a
Stopwatch wrapper around it. I only ran it for a couple of the POCs
(Codedom, Nsubstitute and Emit) so it will be fun to check out the
performance of the action chain. I'll add a unit test for it later.

I think the operator overload is a cool idea and it makes sense to plus
these things together.  Might take some getting use to though if you're not
used to overloaded operators.

**Comment by smatsson** [comment]
@laughinggoose Added performance tests to https://github.com/smatsson/Chainly/blob/master/Source/Chainly.test/Tests/PerformanceTests.cs

Thanks again for contributing :)

**Pull request merged**
